[default_session]
startup_command = "ls"

[[session]]
name = "tmux config"
path = "~"
startup_command = "nvim ~/.tmux.conf"

[[session]]
name = "sesh-tmux config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "nvim config"
path = "~/.config/nvim"
startup_command = "nvim init.lua"

[[session]]
name = "aerospace config"
path = "~/.config/aerospace"
startup_command = "nvim aerospace.toml"

[[session]]
name = "zsh config"
path = "~"
startup_command = "nvim .zshrc"

[[session]]
name = "wezterm config"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "starship config"
path = "~/.config/starship"
startup_command = "nvim starship.toml"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "ls -la"
